### PR TITLE
Rename qt to qt@4, pyqt to pyqt@4

### LINKED ISSUE #5: Rename qt to qt4
I recommend you rename the Qt formula to Qt4 and change `depends_on` accordingly. This is because now that Qt 4 has been removed from Homebrew in https://github.com/Homebrew/homebrew-core/pull/8306/ at some point in the future we'll be renaming the Qt5 formula to just Qt. I'll wait for your 👍 that you're ready before we do that to avoid screwing your tap.

### PR DESCRIPTION
**Pull request by cartr**
Closes #5 by renaming `qt` to `qt@4` and `pyqt` to `pyqt@4` per [the new Homebrew versioning scheme](http://docs.brew.sh/Versions.html). In addition, aliases are added so users who mistakenly type `qt4` or `pyqt4` still install the correct formulae.

The impact on existing users should be minimal – upgrading should migrate the formulae to the new locations (waiting on https://github.com/Homebrew/brew/issues/1770), and external formulae/tutorials that depend on `cartr/qt4/qt` will produce warnings but still work.

Before this gets merged, it would be nice to have updated bottles for legacy macOS versions so CI builds continue to work; @bblacey, would it be possible for you to generate bottles for `qt@4` again like you did the current `qt` bottles?

### CODE REVIEW

**Comment by bblacey** [comment]
@cartr, I believe we will also need to re-generate the the qt and pyqt bottles for this PR.

**Comment by stek29** [comment]
Any news on this?
Am I supposed to somehow checkout `add-at-four` and install `qt@4` if I want to have both qt5 and qt4 installed?

**Comment by cartr** [comment]
@stek29 Currently, it should be OK to install both cartr/qt4/qt and Homebrew/core/qt5 on your system. You don't need to check out this branch for it to work.

In the future, Homebrew would like to rename their Qt5 package so it is called Homebrew/core/qt instead. This hasn't happened yet, but I am preparing for it by renaming my package so it doesn't conflict. Once the package is renamed, `brew update` will fix everything automatically for you.

Which reminds me, this PR is actually pretty out of date and probably won't get merged. I'll probably do the "split into multiple packages" change at the same time as the rename so I can generate bottles more easily.

**Comment by stek29** [comment]
@cartr Oh, haven't noticed that `Homebrew/core/qt` is actually `qt5`...
Thanks. Hope you'll find better solution for splitting into packages.

**Pull request closed without merging**
